# DB + LIQUIBASE
spring.datasource.url=jdbc:postgresql://localhost:5332/
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.liquibase.url=jdbc:postgresql://localhost:5332/
spring.liquibase.user=postgres
spring.liquibase.password=postgres
# OTHERS
frontend.url=localhost:4200
local.running.app=true
